### ISSUE TITLE
Add "Create account" to top navigation bar

### ISSUE THREAD

**Issue by davidhedlund** [TripSit/welcome#1]
It's not obvious that the Wiki is open for editing for anyone with only a "Log in" link that always are seen on the website, see top right on the screenshot.

```<a href="/wiki/Special:UserLogin" title="Special:UserLogin">Log in</a>```

should be companioned with a "Create account" link like this:

``` <a href="/wiki/Special:UserLogin" title="Special:UserLogin&type=signup ">Create account</a><a href="/wiki/Special:UserLogin" title="Special:UserLogin">Log in</a>```

![screenshot from 2017-04-04 06 01 15](https://cloud.githubusercontent.com/assets/6416073/24641016/225fe02c-18fc-11e7-9d51-519b912c2f9d.png)

so it will look on psychonautwiki.org:

![screenshot from 2017-04-04 11 52 22](https://cloud.githubusercontent.com/assets/6416073/24651191/3725ef84-192d-11e7-88d9-a3308225615c.png)

**Comment by davidhedlund** [comment]
Should this repository be renamed to tripsit.me?

Or should I report bugs and freedback for tripsit.me somewhere else on https://github.com/TripSit ?

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
You can always add a requirement like: **Token to prevent spam? Please, ask on the IRC chat #content (link to webchat)**


See "Token to prevent spam?" on the screenshot taken from alsa-project.org

![screenshot from 2017-04-05 08 04 06](https://cloud.githubusercontent.com/assets/6416073/24691877/7504b458-19d6-11e7-8375-44569964197c.png)

**Comment by tacerus** [comment]
Hi,

Sorry for the late reply.
The spam prevention idea is good, although we are still interested in verifying everything we publish prior to doing so.
I know that the Wiki was intended to be more publicly editable, however we are currently not actively endorsing any public and "random" edits in it.
